### ISSUE TITLE
Extension has been removed from Chrome Web Store

### ISSUE THREAD

**Issue by ehmorris** [ehmorris/High-Resolution-Downloader-For-Instagram#19]
Potential solutions to this:
- Distribute via GitHub only
- Re-upload as an unlisted extension
- Alter the screenshots to not include any instagram favicons
- Re-upload with a different title and different screenshots

**Comment by ehmorris** [comment]
In a response received by AppDetex, they stated

> If you offer an app that uses the Instagram APIs or is otherwise compatible with or related to Instagram, you may describe how your application relates to Instagram. For example, you may say that your app is "for Instagram" or that the name of your campaign is "on Instagram".

Seemingly I can change the extension name to "High resolution downloader for Instagram"

**Comment by ehmorris** [comment]
The app has been resubmitted.

> Your item has been submitted and is currently going through a compliance review.
> This review may take up to a few business days to complete. Please check the developer dashboard for the most current state of your item’s review.

**Comment by bamtan** [comment]
Any updates?

**Comment by ehmorris** [comment]
@bamtan I'm waiting on AppDetex to either confirm with me or the web store team that the changes I made are satisfactory. We've exchanged a few emails, and they've said they'll review it, but there's not a lot of incentive for them to get back to me.

While it's off the web store, the extension can be installed by [downloading the source from the latest release](https://github.com/ehmorris/High-Resolution-Downloader-For-Instagram/releases/tag/v2.0.11), and dragging the build.crx file onto `chrome://extensions`.

**Comment by bamtan** [comment]
Thanks for your response, I'm unable to enable the extension installing in this way. "This extension is not listed in the Chrome Web Store and may have been added without your knowledge. [Learn more](https://support.google.com/chrome/?p=ui_remove_non_cws_extensions&hl=en-US)"

**Comment by ehmorris** [comment]
@bamtan try enabling developer mode and trying again. If that doesn't work, try loading the build directory itself. [Here's a zip file of the build directory from the latest release](https://github.com/ehmorris/High-Resolution-Downloader-For-Instagram/files/2087247/build.zip).

To load the extension from this directory:
1. Unzip the folder
2. Go to chrome://extensions ([enable developer mode if you haven't](https://developer.chrome.com/extensions/faq#faq-dev-01))
3. Click "Load Unpacked"
4. Select the unzipped folder

**Comment by ehmorris** [comment]
There's still no movement here from AppDetex or the Chrome Web Store team, and multiple submitted drafts have disappeared with no effect. [I've uploaded the extension again here](https://chrome.google.com/webstore/detail/high-resolution-downloade/hbijmiokbffalbolieapplfhmmnioeao). I'm confident all the trademark issues have been resolved, especially in comparing the new extension to other downloader extensions.

**Comment by ehmorris** [comment]
To add some closure, AppDetex finally got back to me today and said the following:

> While we appreciate that you would like to/have attempted to modify your app, we don’t provide consent to republication and we don’t review of apps prior to publication.

> Please carefully review the relevant policies and guidelines published by Instagram listed below and the policy of Chrome, and publish a new, compliant app.

[Instagram's brand resources page](https://en.instagram-brand.com/guidelines/general), linked in AppDetex's email, says

> If you offer an app, website or a product or service that uses the Instagram APIs or is otherwise compatible with or related to Instagram, you may only use Instagram to say that your app is "for Instagram" or that the name of your campaign is "on Instagram" in a descriptive manner.

So it seems I've done the right thing by renaming and re-uploading the extension.
