### ISSUE TITLE
Extension is not working for the stories anymore.

### ISSUE THREAD

**Issue by starvedhorror** [ehmorris/High-Resolution-Downloader-For-Instagram#41]
Title. Buttons simply do not appear. Looks like Instagram changed something, since it is also impossible to click on a username on top of the story. (That has nothing to do with the extension though, it doesn't work in any case)

**Comment by starvedhorror** [comment]
Instagram changed something again, and it's working. *sigh*

**Comment by ehmorris** [comment]
Ah that's good news. Thanks for leaving a report!
