### ISSUE TITLE
UI can take seconds to appear after clicking

### ISSUE THREAD

**Issue by ehmorris** [ehmorris/High-Resolution-Downloader-For-Instagram#48]
This is probably related to this PR: https://github.com/ehmorris/High-Resolution-Downloader-For-Instagram/pull/46

![Screencast](https://user-images.githubusercontent.com/654275/63966719-daa2f400-ca69-11e9-8746-97059ec8be03.gif)

A loader should at least be shown instantly after clicking.

**Comment by willieip** [comment]
pLz Fix I can't live
