### ISSUE TITLE
High Resolution Downloader doesn't work inside instagram DM

### ISSUE THREAD

**Issue by isolationcooks** [ehmorris/High-Resolution-Downloader-For-Instagram#53]
#### Expected Behavior

- Download, Open in tab shows up over images in instagram direct messages

#### Actual Behavior

- Images in instagram direct messages do not have this overlay
 
#### Steps To Reproduce The Behavior

- Install High Resolution Downloader for Instagram on Chrome, go to instagram direct messages on the desktop, click on any image in direct messages, and in the resulting modal there is no prompt for download

![image](https://user-images.githubusercontent.com/65801833/82722201-25445a80-9ce2-11ea-8abf-a33ef8b7be83.png)

![image](https://user-images.githubusercontent.com/65801833/82722213-3db47500-9ce2-11ea-88ca-81d9fb9fdda2.png)

**Comment by ehmorris** [comment]
This is a great issue report, thank you! I will look into this.

**Comment by ehmorris** [comment]
Hey there, I just had the chance to try to reproduce this and wasn’t able. I DM’d myself a video post, photo post, and story. Clicking any of these media types in a DM opened that media’s standalone page, not a modal.

There’s a chance IG is A/B testing different ways of showing media in DMs.

**Comment by isolationcooks** [comment]
I believe the issue was encountered when an image or video was sent using
the following feature on the desktop
[image: image.png]

or on the mobile

[image: image.png]

I can confirm that sharing a post or story takes you to the specific post.

**Comment by ehmorris** [comment]
Ahh thank you. It turns out this was just a z-index issue. I'll release a fix.

**Comment by ehmorris** [comment]
I've submitted this update to the Chrome Webstore.

**Comment by isolationcooks** [comment]
It's working as intended now! Thank you for looking into this, it's
extremely helpful.
