### ISSUE TITLE
Include packed extension in releases

### ISSUE THREAD

**Issue by kdkasad** [ehmorris/High-Resolution-Downloader-For-Instagram#60]
It would be great if you could include the extension file in the Releases section on GitHub. That way the pre-built extension is available without giong through Google.

**Comment by ehmorris** [comment]
I do update and include the build.crx file in each release. You should be able to install it like this:

![demo](https://user-images.githubusercontent.com/654275/101259934-28d98500-36fa-11eb-9dbe-c071d98c9694.gif)
