### ISSUE TITLE
Download/open in tab buttons no longer appear in stories

### ISSUE THREAD

**Issue by paulschreiber** [ehmorris/High-Resolution-Downloader-For-Instagram#62]
#### Steps To Reproduce The Behavior
- Open an Instagram story
- Click on photo or video

#### Expected Behavior
- "Download" and "Open in Tab" buttons appear

#### Actual Behavior
- No change

#### Config 

- Chrome 87.0.4280.88
- macOS 10.15.7
- HRDFI 2.0.26

**Comment by paulschreiber** [comment]
…and it's working now.

**Comment by ehmorris** [comment]
I think Instagram has been tweaking the new stories format. I've had to release two fixes:

* https://github.com/ehmorris/High-Resolution-Downloader-For-Instagram/releases/tag/v2.0.26
* https://github.com/ehmorris/High-Resolution-Downloader-For-Instagram/releases/tag/v2.0.27

Thanks for the report nonetheless!
